---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
  - package-ecosystem: npm
    directory: "/scripts/gh-resto"
    schedule:
      interval: "daily"
